language: node_js

os:
  - linux
  - osx
  # - windows

# https://github.com/nodejs/Release#nodejs-release-working-group
node_js:
  - 10
  - 12
  - 13
  - 14

script:
  - npm run bootstrap
  - npm run build
  - npm run lint
  - npm test

notifications:
  email: false
